- client/src/pages/Login/Login.styles.ts
- client/src/pages/Login/Login.tsx
- client/src/pages/Signup/Signup.styles.ts
- client/src/pages/Signup/Signup.tsx
- Also changed the UI feel of the form input fields. On focus, input fields will now show a subtle glow around the selected field
- Added states that keep track of login email and password - Left the Form Submission function logic empty for now
> UI Ticket: Added fields for first and last name in signup form

- client/src/App.tsx
- client/src/components/BudgetNavbar/BudgetNavbar.styles.ts
- client/src/components/BudgetNavbar/BudgetNavbar.tsx
- client/src/components/IncomeAdder/IncomeAdder.styles.ts
- client/src/components/IncomeAdder/IncomeAdder.tsx
- client/src/components/IncomeItem/IncomeItem.styles.ts
- client/src/components/IncomeItem/IncomeItem.tsx
- client/src/components/IncomeTracker/IncomeTracker.styles.ts
- client/src/components/IncomeTracker/IncomeTracker.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/components/index.tsx
- client/src/pages/Budget/Budget.styles.ts
- client/src/pages/Budget/Budget.tsx
- client/src/pages/Combined/Combined.tsx
- client/src/pages/ErrorPage/ErrorPage.styles.ts
- client/src/pages/ErrorPage/ErrorPage.tsx
- client/src/pages/Expenses/Expenses.tsx
- client/src/pages/Income/Income.tsx
- client/src/pages/index.tsx
- Created the Income Page with Two components - IncomeAdder and IncomeTracker
- Created a Nested Route using React Router so that user can goto see his/her budget - then select a tab from the sub navigation bar with options of Income/Expenses/Combined
- Added some subtle animations for Income Page when IncomeAdder component gets brought in
> UI Ticket 8 - Created Income Page

- client/src/components/IncomeAdder/IncomeAdder.styles.ts
- client/src/components/IncomeAdder/IncomeAdder.tsx
- client/src/components/IncomeItem/IncomeItem.styles.ts
- client/src/components/IncomeItem/IncomeItem.tsx
- client/src/components/IncomeTracker/IncomeTracker.styles.ts
- client/src/components/IncomeTracker/IncomeTracker.tsx
- client/src/components/Navigation/Navigation.styles.ts
- client/src/components/Navigation/Navigation.tsx
- client/src/index.css
- client/src/pages/Home/Home.styles.ts
- client/src/pages/Income/Income.styles.ts
- client/src/pages/Income/Income.tsx
Sorry for the confusion in ticket name - I first created the ticket to work on the Dashboard page but ended up just making some improvements to the income page. I'll need to learn later how to change the branch names to avoid this type of confusion
Here are the things I've implemented:
- Added max-width to the Income Container so that desktop view does not look too big
- Moved the Income Adder component to the top whenever User wants to add in a new income item. Will maybe look into adding a scrollbar within the Income Tracker component itself so that the page does not get too long as more items are added
- Added UI functionality for adding and deleting income items.
Things to work on further:
- Maybe implement a scroll bar inside the Income Tracker component so that the page itself does …
> UI: Made improvements to the Income Page

- client/src/API/AuthMethods.ts
- client/src/components/TransactionItemAdder/TransactionItemAdder.tsx
- client/src/pages/Login/Login.styles.ts
- client/src/pages/Signup/Signup.styles.ts
- client/src/pages/Signup/Signup.tsx
- server/src/Auth/auth.dto.ts
- server/src/Auth/auth.interfaces.ts
- server/src/Auth/auth.schema.ts
- server/src/Auth/auth.service.ts
- server/src/Transactions/transaction.controller.ts
- server/src/Transactions/transaction.service.ts
In this PR:
-Added signUp validation
-made a few style changes to account for future error messages in logIn validation
-fixed a few types
> Feat: Sign up validation

- client/src/components/Navigation/Navigation.styles.ts
- client/src/components/Navigation/Navigation.tsx
- Sidebar no longer flashes whenever refreshing
- Signup and Login button will now show black background and white font color only when selected from desktop navigation
> UI fixes to Navigation

- client/src/App.css
- Added overflow: hidden in app.css so that scrollbar doesn't flash due to animation
> Scrollbar Fix

- client/src/API/AuthMethods.ts
- client/src/App.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/pages/Login/Login.tsx
- client/src/pages/Signup/Signup.tsx
- server/src/Auth/auth.service.ts
- server/src/Transactions/schema/transaction.schema.ts
I fixed our routing bugs and added the logOut method so that everyone is routed to the correct places. Please make sure I didn't miss anything at the logOut functionality.
> Bug: Fixed auth methods

- client/src/App.tsx
- client/src/components/Navigation/Navigation.styles.ts
- client/src/components/Navigation/Navigation.tsx
- client/src/pages/Transactions/Transactions.tsx
- Logout button is no longer highlighted
- Refreshing the page no longer logs out the user
- Expense items are now being retrieved correctly
> Fixes for refresh, logout button, and expense items loading

- client/src/components/BudgetNavbar/BudgetNavbar.styles.ts
- client/src/components/BudgetNavbar/BudgetNavbar.tsx
- server/src/Transactions/transaction.controller.ts
- Budget navbar had a visual bug where it would highlight the wrong option when refreshed. Now it is highlighted only when the link is active
> Fixed Budget Navbar

- server/src/Transactions/transaction.controller.ts
- server/src/Transactions/transaction.module.ts
- server/src/Transactions/transaction.service.ts
I went through and fixed the editing and deleting methods on the back end.  I also commented out the getById method since I don't think we will need that method going forward.  This PR needs to be approved and merged in for Ben's work on the edit feature to work.  Also, @bycho91, don't worry about making a search for each transaction.  Just get the edit/delete features working and we will be good to move on to our next feature: The dashboard view!
> Fix: Tweaking be transaction methods

- client/src/API/TransactionMethods.ts
- client/src/App.tsx
- client/src/components/BudgetNavbar/BudgetNavbar.styles.ts
- client/src/components/BudgetNavbar/BudgetNavbar.tsx
- client/src/components/TransactionItem/TransactionItem.tsx
- client/src/components/TransactionItemEditor/TransactionItemEditor.styles.ts
- client/src/components/TransactionItemEditor/TransactionItemEditor.tsx
- client/src/components/TransactionItemsList/TransactionItemsList.tsx
- client/src/components/index.tsx
- client/src/pages/Combined/Combined.styles.ts
- client/src/pages/Combined/Combined.tsx
- client/src/pages/Transactions/Transactions.tsx
- client/src/pages/index.tsx
- User can now click on an item and slide out option for edit and delete
- User can click the edit icon to bring up a modal with the Transaction Item's Title and Amount prefilled
- User can change and click submit - Giving a 401 unauthorized error for some reason
- User can click the close icon on modal to close the modal.
- getItem API method in TransactionMethods was commented out for now - let me know if I should just delete it altogether
> Edit Feature

- client/src/App.css
- client/src/dummydata.ts
- client/src/pages/Home/Home.styles.ts
- client/src/pages/Home/Home.tsx
- Created the styled components according to the Figma design for dashboard page
- Using dummy data defined in dummydata.ts file
- Responsiveness for container width on desktop view
- Color of bar will change conditionally based on whether budget is fully spent or not
- Clicking the Adjust Income/Adjust Expense links will take user to the Budget Income/Expense pages
> UI dashboard

- client/src/components/BudgetCard/BudgetCard.styles.ts
- client/src/components/BudgetCard/BudgetCard.tsx
- client/src/components/BudgetCardList/BudgetCardList.styles.ts
- client/src/components/BudgetCardList/BudgetCardList.tsx
- client/src/components/index.tsx
- client/src/constants.ts
- client/src/dummydata.ts
- client/src/pages/Home/Home.styles.ts
- client/src/pages/Home/Home.tsx
Broke up the gigantic Home.tsx file into more digestible components
Still using dummy data for now, but set up so that I can easily just make API call to retrieve data from BE
Hierarchy is as follows:
- Home Page > BudgetCardList component > BudgetCard component
> UI-Dashboard Improvements

- client/src/pages/Home/Home.styles.ts
- client/src/pages/Home/Home.tsx
fixed the merge conflicts on home.tsx file
> Fixed Home.tsx file

- server/package-lock.json
- server/package.json
- server/src/Budgets/budget.controller.ts
- server/src/Budgets/budget.service.ts
- server/src/Budgets/dataStructureFiles/budget.dto.ts
- server/src/Budgets/dataStructureFiles/budget.interfaces.ts
- server/src/Budgets/dataStructureFiles/budget.schema.ts
- server/src/Budgets/utils.ts
Created a method to serve up budget titles from the back end.  These should be consumed on the front end and displayed for the user to choose from. Once they have picked for one to be created, then you send that info back to the backend via the createBudget method.
Pay attention to the data shapes as they have changed.  The back end now expects a title, total, currentAmount, and created properties.
> Feat: Created a method to serveUpBudgetTitles

- server/src/Budgets/budget.service.ts
- server/src/Transactions/dataStructureFiles/transaction.interfaces.ts
- server/src/Transactions/dataStructureFiles/transaction.schema.ts
- server/src/Transactions/transaction.controller.ts
- server/src/Transactions/transaction.service.ts
-Incomes and Expenses are now bound to budgets.
-Pass the budget._id as a param when creating incomes and expenses.
-When budgets are created, the "created" property is changed to "true."
> Feat: Connecting transactions to budgets

- server/src/Budgets/budget.controller.ts
- server/src/Budgets/budget.service.ts
- server/src/Budgets/dataStructureFiles/budget.interfaces.ts
- server/src/Budgets/utils.ts
@bycho91, look closely at this code.  There is a lot going on here.  But it should work the way you wanted.  I am sending you back some dummy data for budgets that haven't been created yet.  So they will look like a budget but be missing a user_id, budget_id etc.  This should work!
> Edited backend getAllBudgets

- client/package-lock.json
- client/package.json
- client/src/API/BudgetMethods.ts
- client/src/components/BudgetAdder/BudgetAdder.styles.ts
- client/src/components/BudgetAdder/BudgetAdder.tsx
- client/src/components/BudgetCard/BudgetCard.styles.ts
- client/src/components/BudgetCard/BudgetCard.tsx
- client/src/components/BudgetCardList/BudgetCardList.styles.ts
- client/src/components/BudgetCardList/BudgetCardList.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/components/index.tsx
- client/src/constants.ts
- client/src/pages/Home/Home.styles.ts
- client/src/pages/Home/Home.tsx
- Added carousel to dashboard page - renders out 2 years worth of budgets (both active and inactive)
- User can click arrow to navigate through the carousel
- User can create a budget by clicking the plus icon and inputting the amount they'd like to budget out for the month
- Once user submits the Budget Adder form with valid budget amount - UI of carousel card for that month will change to active status
- Goto Current button will allow user to go back to the current month faster without having to click all the way back or forward
Things that may need more work:
Carousel may not be best in terms of responsiveness to viewport changes
> Dashboard Improvements

- server/src/Budgets/budget.service.ts
- server/src/Budgets/utils.ts
- server/src/Transactions/dataStructureFiles/transaction.schema.ts
- server/src/Transactions/transaction.controller.ts
- server/src/Transactions/transaction.module.ts
- server/src/Transactions/transaction.service.ts
In this PR I:
- heavily edited the transactions methods so that now all you have to do is feed them a negative amount for them to be saved as expenses and a positive amount to be saved as incomes.
- creating transactions also require a budget ID so that they can belong to that budget.
- I also edited the return array from getAllBudgets so that you only get a title string of "MONTH  YEAR" or a created budget.
Please check to make sure everything works in postman to match what you need on the front.
> Refactor: Restructuring transaction methods

- server/src/Budgets/budget.service.ts
- server/src/Budgets/dataStructureFiles/budget.interfaces.ts
- server/src/Budgets/utils.ts
Added back in the dummy budget functionality.
> Quick dummy budget fix

- server/src/FinanceTips/constants.ts
- server/src/FinanceTips/dataStructureFiles/financeTips.interfaces.ts
- server/src/FinanceTips/financeTips.module.ts
- server/src/FinanceTips/financeTips.service.ts
- server/src/FinanceTips/financialTips.controller.ts
- server/src/app.module.ts
In this PR: 
- I added all code for finance tips.  It is really easy to add them manually to our array in the constants file.
- The tips are not guarded but user's shouldn't have access to the FE end method to pull them anyway.
- This should be a FE method strictly to display the tips.  Everything is readonly and cannot be altered unless the array is manually altered on the BE.
- I am open to adding more and different tips.
> Feat: Financial tips

- server/src/Budgets/budget.controller.ts
In this PR:
- I added a method on the BE to getBudgetById.
- Make sure to test in postman.
- let me know if you need any other changes to it.
> Feat: getBudgetById method

- client/src/components/TransactionItemAdder/TransactionItemAdder.tsx
- client/src/components/TransactionItemEditor/TransactionItemEditor.tsx
- client/src/components/TransactionItemsList/TransactionItemsList.styles.ts
- client/src/components/TransactionItemsList/TransactionItemsList.tsx
- client/src/constants.ts
- client/src/pages/BudgetMain/BudgetMain.tsx
- client/src/pages/Transactions/Transactions.tsx
- Changed the type of budgetData from 'any' to 'IBudget'
> IBudget Interface

- client/src/API/BudgetMethods.ts
- client/src/components/BudgetCard/BudgetCard.styles.ts
- client/src/components/BudgetCard/BudgetCard.tsx
- client/src/components/TransactionItemAdder/TransactionItemAdder.tsx
- client/src/components/TransactionItemEditor/TransactionItemEditor.styles.ts
- client/src/components/TransactionItemEditor/TransactionItemEditor.tsx
- client/src/pages/Budget/Budget.tsx
- client/src/pages/BudgetMain/BudgetMain.tsx
- Please ignore branch name lol
- Added the front end method for getting budget by ID
- Fixed the styling for the Adder to be position:fixed
> Added Get Budget By ID method

- client/src/App.css
- client/src/components/BudgetCard/BudgetCard.styles.ts
- client/src/components/BudgetCard/BudgetCard.tsx
- client/src/components/BudgetCardList/BudgetCardList.styles.ts
- client/src/components/BudgetCardList/BudgetCardList.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/pages/Budget/Budget.tsx
- client/src/pages/BudgetMain/BudgetMain.styles.ts
- client/src/pages/BudgetMain/BudgetMain.tsx
- client/src/pages/Home/Home.styles.ts
- client/src/pages/Home/Home.tsx
- client/src/pages/Transactions/Transactions.styles.ts
- client/src/pages/Transactions/Transactions.tsx
- Created UI for Main Budget Page
- Fixed some stuff for carousel of budget cards according to Jonathan's comments
- User now has access to a button that'll allow them to go back to the specific budgets main page
- Navigation bar no longer has 'My Budget' option. Only Home and Logout
> Main Budget Page + fixes

- client/src/components/BudgetCard/BudgetCard.styles.ts
- client/src/components/BudgetCard/BudgetCard.tsx
- client/src/components/BudgetEditor/BudgetEditor.styles.ts
- client/src/components/BudgetEditor/BudgetEditor.tsx
- client/src/components/TransactionItem/TransactionItem.tsx
- client/src/components/TransactionItemAdder/TransactionItemAdder.tsx
- client/src/components/TransactionItemEditor/TransactionItemEditor.tsx
- client/src/components/TransactionItemsList/TransactionItemsList.tsx
- client/src/components/index.tsx
- client/src/pages/Budget/Budget.tsx
- client/src/pages/BudgetMain/BudgetMain.styles.ts
- client/src/pages/BudgetMain/BudgetMain.tsx
- client/src/pages/Transactions/Transactions.styles.ts
- client/src/pages/Transactions/Transactions.tsx
- any time I used useOutletContext - I typed this as <any> because I couldn't figure out how to get it without it throwing an error. But everything works as intended for now, so I just need help figuring out this type
- User can now add transaction and edit transaction at any time - The currentAmount property of the budget should update correctly
> Fixed Edit/Delete Transaction to correctly update budget's current amount

- client/src/components/BudgetAdder/BudgetAdder.tsx
In this PR: 
- I changed the role of the button from ```submit``` to ```button```.
> Bug: Fix budget validation

- client/src/components/Loading/Loading.tsx
In this PR: 
- I changed the loading circle color.
> Style: Change loading circle color

- client/src/API/FinancialTipMethods.ts
- client/src/components/Loading/Loading.tsx
- client/src/constants.ts
- Loading page will now pull quotes from BE and pick a random quote to show in UI
> Loading Page with Quotes from BE

- client/src/components/BudgetAdder/BudgetAdder.tsx
- client/src/components/BudgetEditor/BudgetEditor.tsx
Reverts bretpeters3n/seal-team-3#106
> Revert "Fix: More budget amount formatting bugs"

- client/src/components/BudgetCard/BudgetCard.tsx
- client/src/components/BudgetCardList/BudgetCardList.styles.ts
- client/src/components/BudgetCardList/BudgetCardList.tsx
- client/src/components/Loading/Loading.styles.ts
- client/src/components/TransactionItemAdder/TransactionItemAdder.styles.ts
- client/src/components/TransactionItemAdder/TransactionItemAdder.tsx
- client/src/components/TransactionItemEditor/TransactionItemEditor.styles.ts
- client/src/components/TransactionItemEditor/TransactionItemEditor.tsx
- client/src/constants.ts
- client/src/pages/BudgetMain/BudgetMain.tsx
- client/src/pages/Home/Home.styles.ts
- Added the same currency formatting for transactions adding and editing.
- Go to Current Month budget button - changed styling to match other buttons, changed the placement and took out the word 'budget' at the end. Let me know if you want to just keep that as it was, but I think it was too lengthy
- Loading component was made a bit smaller so that itll fit mobile views better
> Currency Format for Transaction Adder and Editor

- client/src/components/BudgetCard/BudgetCard.tsx
- client/src/components/BudgetCardList/BudgetCardList.styles.ts
- client/src/components/TransactionItemsList/TransactionItemsList.styles.ts
- client/src/pages/Home/Home.styles.ts
- Small fixes for spacing in the dashboard container
- Scrollbar within the transaction items list will now only show once it starts overflowing
> Other UI fixes
